### ISSUE TITLE
[BUG]: Problema com fontes no linux

### ISSUE THREAD

**Issue by maiconrp** [maiconrp/adgestao#30]
## Descreva o erro
Ao rodar o site, seja fazendo uma migração ou runserver, o sistema levanta o erro: `Can't open file "arial.ttf"
`

## Para reproduzir
Execute um dos seguintes comandos:`migrate`, `makemigrations`, `runserver`

## Comportamento esperado
O comum seria o site se executar normalmente, no caso do makemigrations, preparar a migração. No migrate, migrar. E no runserver, executar o server, rodando o site

## Capturas de tela
```
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 537, in open_for_read
    return open_for_read_by_name(name,mode)
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 477, in open_for_read_by_name
    return open(name,mode)
FileNotFoundError: [Errno 2] No such file or directory: 'arial.ttf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 544, in open_for_read
    return BytesIO((datareader if name[:5].lower()=='data:' else rlUrlRead)(name))
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 490, in rlUrlRead
    return urlopen(name).read()
  File "/usr/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python3.10/urllib/request.py", line 503, in open
    req = Request(fullurl, data)
  File "/usr/lib/python3.10/urllib/request.py", line 322, in __init__
    self.full_url = url
  File "/usr/lib/python3.10/urllib/request.py", line 348, in full_url
    self._parse()
  File "/usr/lib/python3.10/urllib/request.py", line 377, in _parse
    raise ValueError("unknown url type: %r" % self.full_url)
ValueError: unknown url type: 'arial.ttf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 151, in TTFOpenFile
    f = open_for_read(fn,'rb')
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 548, in open_for_read
    return open_for_read(name,mode)
  File "/usr/lib/python3/dist-packages/reportlab/lib/utils.py", line 546, in open_for_read
    raise IOError('Cannot open resource "%s"' % name)
OSError: Cannot open resource "arial.ttf"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/aluno/Área de Trabalho/adgestao/code/manage.py", line 22, in <module>
    main()
  File "/home/aluno/Área de Trabalho/adgestao/code/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 442, in execute_from_command_line
    utility.execute()
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/management/__init__.py", line 436, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/management/base.py", line 412, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/management/base.py", line 453, in execute
    self.check()
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/management/base.py", line 485, in check
    all_issues = checks.run_checks(
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/checks/registry.py", line 88, in run_checks
    new_errors = check(app_configs=app_configs, databases=databases)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/checks/urls.py", line 14, in check_url_config
    return check_resolver(resolver)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/core/checks/urls.py", line 24, in check_resolver
    return check_method()
  File "/home/aluno/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 494, in check
    for pattern in self.url_patterns:
  File "/home/aluno/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/aluno/.local/lib/python3.10/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/aluno/Área de Trabalho/adgestao/code/adgestao/urls.py", line 19, in <module>
    import financas.urls
  File "/home/aluno/Área de Trabalho/adgestao/code/adgestao/../apps/financas/urls.py", line 2, in <module>
    from .views import *
  File "/home/aluno/Área de Trabalho/adgestao/code/adgestao/../apps/financas/views.py", line 19, in <module>
    pdfmetrics.registerFont(TTFont("Arial", "arial.ttf"))
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 1178, in __init__
    self.face = TTFontFace(filename, validate=validate, subfontIndex=subfontIndex)
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 1072, in __init__
    TTFontFile.__init__(self, filename, validate=validate, subfontIndex=subfontIndex)
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 439, in __init__
    TTFontParser.__init__(self, file, validate=validate,subfontIndex=subfontIndex)
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 175, in __init__
    self.readFile(file)
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 251, in readFile
    self.filename, f = TTFOpenFile(f)
  File "/usr/lib/python3/dist-packages/reportlab/pdfbase/ttfonts.py", line 161, in TTFOpenFile
    raise TTFError('Can\'t open file "%s"' % fn)
reportlab.pdfbase.ttfonts.TTFError: Can't open file "arial.ttf"
```

## Dispositivo
* [ ] Smartphone
* [x] Desktop

**Comment by maiconrp** [comment]
## Solução
```
sudo apt install ttf-mscorefonts-installer
```

## Explicação
A geração de pdf usa a fonte "Arial", que por padrão não vem instalada no linux

Mais detalhes [aqui](https://diolinux.com.br/sistemas-operacionais/instalando-fontes-no-linux.html)
